global:
  scrape_interval: 15s  # Як часто опитувати "шпигунів" (кожні 15 сек)

scrape_configs:
  # 1. Завдання: Стежити за самим собою (щоб знати, чи живий Prometheus)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Завдання: Стежити за сервером (Node Exporter)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
      # 'node_exporter' - це буде ім'я контейнера в docker-compose.
      # 9100 - стандартний порт шпигуна.
