services:
  web:
    build: .
    ports:
      - "${APP_PORT}:80"
  backend:
    image: traefik/whoami:latest
  backup:
    build: .
    command: /bin/bash -c "/usr/local/bin/backup.sh >> /usr/share/nginx/html/backup/backup.log 2>&1"
    volumes:
      - "./backups:/usr/share/nginx/html/backup"
