name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # <--- Головна зміна! Ми кажемо "запустись на моєму комп'ютері"
    steps:
      - uses: actions/checkout@v3          # <--- КРОК 1: Скачати код з GitHub
      - name: Run Ansible Playbook
        env:
          ANSIBLE_BECOME_PASS: ${{ secrets.ANSIBLE_SUDO_PASS }}
        run: |
          cd /home/user/ansible-learn # Заходимо в папку, де лежать плейбуки
          ansible-playbook -i inventory.ini setup.yml
